config/routes.rb
Rails.application.routes.draw do
  resources :products do
    member do
      post 'add_to_cart'
    end
  end

  root 'products#index'

end

app/models/category.rb
class Category < ActiveRecord::Base

  acts_as_list

  has_many :product_categories
  has_many :products, through: :product_categories

  scope :sorted, -> { order(:position) }

end

app/models/product.rb
class Product < ActiveRecord::Base

  has_many :product_categories
  has_many :categories, through: :product_categories

end

app/models/product_category.rb
class ProductCategory < ActiveRecord::Base
  belongs_to :product
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
  end

  def add_to_cart
    product_id = params[:id]

    if cookies[:cart].present?
      products = cookies[:cart].split(',')
      products << product_id
      cookies[:cart] = products.join(',')
    else
      cookies[:cart] = product_id
    end

    redirect_to :back

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myshop</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/_product.html.erb
<%= product.name %>
<br/>
<%= number_to_currency(product.price, unit: 'грн.', format: '%n %u', separator: ',') %>
<br/>
<%= button_to 'Add to cart', add_to_cart_product_path(product) %>

app/views/products/index.html.erb
<%= render @products %>

__ <br/>
<%= cookies[:cart] %>